### ISSUE TITLE
Port config for scheduler is incorrect   (59861->59863)

### ISSUE THREAD

**Issue by SynchronicIT** [edgexfoundry/edgex-ui-go#840]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]
service-scheduler in edgex-go uses different port number than used in the configure.xml. 

Core-Keeper should be able to overrule this based upon the registration of the service, but this doesn't work for the ui. 

### Is this a regression?

Could be false for a longer time. Not sure as we kicked out Consult and moved to static configuration in the past. 

### Description and Minimal Reproduction [**REQUIRED**]

Run the default docker compose examples and check the scheduler in the UI. 

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version 4.0: clean installation**

**Comment by ytakio** [comment]
Does anyone know how progress it is? Are there any workaround?

**Comment by cloudxxx8** [comment]
There is no maintainer of this repository so far

**Comment by SynchronicIT** [comment]
I don't mind taking up the task as maintainer. As there are more points which we see room for improvement (e.g. ui for core-keeper)

**Comment by cloudxxx8** [comment]
I believe the first step is to upgrade all the packages / depenedencies.
It's a little outdated.

**Comment by lamalexck** [comment]
I hacked the configuration file to use port 59863, but I see in the UI.

```
edgex code: undefined , message: Not Found
```

Are these still valid?

```
Registry:
    Host: edgex-core-consul
    Port: 8500
    Type: consul
    ConfigRegistryStem: edgex/
    ServiceVersion: 'v3'
APIGateway:
    Server: edgex-nginx
    ApplicationPort: 8000
    ApplicationPortSSL: 8443
```
